#!/usr/bin/env python3
"""Read protocols/manifest.toml and emit CMake codegen + fetch lists."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    import tomllib
except ImportError:  # pragma: no cover
    import tomli as tomllib  # type: ignore


def load_manifest(path: Path) -> dict:
    return tomllib.loads(path.read_text(encoding="utf-8"))


def protocol_entries(manifest: dict, section: str) -> list[dict]:
    block = manifest.get(section, {})
    entries = block.get("protocol", [])
    if isinstance(entries, dict):
        return [entries]
    return list(entries)


def all_protocol_entries(manifest: dict) -> list[dict]:
    return (
        protocol_entries(manifest, "upstream")
        + protocol_entries(manifest, "wlr")
        + protocol_entries(manifest, "lumen")
    )


def emit_cmake(manifest: dict, root: Path, out: Path, priorities: set[str]) -> None:
    lines = [
        "# Auto-generated by scripts/protocol_manifest.py — do not edit",
        "set(LUMEN_GENERATED_PROTOCOL_SOURCES \"\")",
        "set(LUMEN_PROTOCOL_GLUE_SOURCES \"\")",
        "set(LUMEN_PROTOCOL_GLUE_HEADERS \"\")",
        "",
    ]

    for entry in all_protocol_entries(manifest):
        priority = entry.get("priority", "P2")
        if priority not in priorities:
            continue
        rel = entry["path"]
        # upstream XML lives under protocols/upstream/ after fetch-protocols.sh
        if not rel.startswith("lumen/"):
            rel = f"upstream/{rel}"
        module = entry["module"]
        xml = (root / "protocols" / rel).as_posix()
        xml_stem = Path(rel).stem  # wayland, xdg-shell, …
        # Core wayland.xml: skip C glue — headers/symbols ship with libwayland-server.
        skip_glue = xml_stem == "wayland"
        lines += [
            f"# {module} ({priority})",
            f'set(_LUMEN_XML "{xml}")',
            'if(EXISTS "${_LUMEN_XML}")',
            "  lumen_generate_protocol(",
            '    "${_LUMEN_XML}"',
            f'    "{module}"',
            "    _LUMEN_GEN",
            "  )",
            "  list(APPEND LUMEN_GENERATED_PROTOCOL_SOURCES ${_LUMEN_GEN})",
        ]
        if not skip_glue:
            lines += [
                "  lumen_generate_protocol_glue(\"${_LUMEN_XML}\")",
                f'  list(APPEND LUMEN_PROTOCOL_GLUE_HEADERS '
                f'"${{LUMEN_GENERATED_DIR}}/{xml_stem}-server-protocol.h")',
                f'  list(APPEND LUMEN_PROTOCOL_GLUE_HEADERS '
                f'"${{LUMEN_GENERATED_DIR}}/{xml_stem}-client-protocol.h")',
                f'  list(APPEND LUMEN_PROTOCOL_GLUE_SOURCES '
                f'"${{LUMEN_GENERATED_DIR}}/{xml_stem}-protocol.c")',
            ]
        lines += [
            "else()",
            f'  message(STATUS "Protocol XML not found: {rel}")',
            "endif()",
            "",
        ]

    # Included at top level via include() — no PARENT_SCOPE.
    lines.append(
        'set(LUMEN_GENERATED_PROTOCOL_SOURCES "${LUMEN_GENERATED_PROTOCOL_SOURCES}")'
    )
    lines.append(
        'set(LUMEN_PROTOCOL_GLUE_SOURCES "${LUMEN_PROTOCOL_GLUE_SOURCES}")'
    )
    lines.append(
        'set(LUMEN_PROTOCOL_GLUE_HEADERS "${LUMEN_PROTOCOL_GLUE_HEADERS}")'
    )
    out.parent.mkdir(parents=True, exist_ok=True)
    # Always LF endings so generated CMake is portable across hosts.
    out.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


def emit_fetch_list(manifest: dict, out: Path) -> None:
    upstream = manifest.get("upstream", {})
    tag = upstream.get("wayland_protocols_tag", "1.44")
    lines = [f"TAG={tag}"]
    seen: set[str] = set()

    for entry in protocol_entries(manifest, "upstream"):
        src = entry.get("source", "wayland-protocols")
        path = entry["path"]
        key = f"{src}|{path}"
        if key not in seen:
            lines.append(key)
            seen.add(key)

    for entry in protocol_entries(manifest, "wlr"):
        path = entry["path"]
        key = f"wlr|{path}"
        if key not in seen:
            lines.append(key)
            seen.add(key)

    if "wayland|wayland.xml" not in seen:
        lines.append("wayland|wayland.xml")

    out.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--manifest", type=Path, default=None)
    parser.add_argument("--cmake-out", type=Path, default=None)
    parser.add_argument("--fetch-out", type=Path, default=None)
    parser.add_argument("--priorities", default="P0,P1")
    args = parser.parse_args()

    manifest_path = args.manifest or args.root / "protocols" / "manifest.toml"
    manifest = load_manifest(manifest_path)
    priorities = set(p.strip() for p in args.priorities.split(",") if p.strip())

    if args.cmake_out:
        emit_cmake(manifest, args.root, args.cmake_out, priorities)
    if args.fetch_out:
        emit_fetch_list(manifest, args.fetch_out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
